
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMILLADOBLE EXECUTE FIT ID IGUAL MKDISK NUMERO PATH RUTA SIZE UNITcommand : mkdisk_command\n               | execute_commandmkdisk_command : MKDISK opcionesopciones : opciones opciones_element \n                | opciones_elementopciones_element : opcion_size\n                        | opcion_path\n                        | opcion_unit\n                        | opcion_fitopcion_size : SIZE IGUAL NUMEROopcion_path : PATH IGUAL RUTA\n                   | PATH IGUAL COMILLADOBLE RUTA COMILLADOBLEopcion_unit : UNIT IGUAL IDopcion_fit : FIT IGUAL IDexecute_command : EXECUTE PATH IGUAL RUTA\n                       | EXECUTE PATH IGUAL COMILLADOBLE RUTA COMILLADOBLE'
    
_lr_action_items = {'MKDISK':([0,],[4,]),'EXECUTE':([0,],[5,]),'$end':([1,2,3,6,7,8,9,10,11,17,23,24,26,27,28,32,33,],[0,-1,-2,-3,-5,-6,-7,-8,-9,-4,-10,-11,-13,-14,-15,-12,-16,]),'SIZE':([4,6,7,8,9,10,11,17,23,24,26,27,32,],[12,12,-5,-6,-7,-8,-9,-4,-10,-11,-13,-14,-12,]),'PATH':([4,5,6,7,8,9,10,11,17,23,24,26,27,32,],[13,16,13,-5,-6,-7,-8,-9,-4,-10,-11,-13,-14,-12,]),'UNIT':([4,6,7,8,9,10,11,17,23,24,26,27,32,],[14,14,-5,-6,-7,-8,-9,-4,-10,-11,-13,-14,-12,]),'FIT':([4,6,7,8,9,10,11,17,23,24,26,27,32,],[15,15,-5,-6,-7,-8,-9,-4,-10,-11,-13,-14,-12,]),'IGUAL':([12,13,14,15,16,],[18,19,20,21,22,]),'NUMERO':([18,],[23,]),'RUTA':([19,22,25,29,],[24,28,30,31,]),'COMILLADOBLE':([19,22,30,31,],[25,29,32,33,]),'ID':([20,21,],[26,27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'mkdisk_command':([0,],[2,]),'execute_command':([0,],[3,]),'opciones':([4,],[6,]),'opciones_element':([4,6,],[7,17,]),'opcion_size':([4,6,],[8,8,]),'opcion_path':([4,6,],[9,9,]),'opcion_unit':([4,6,],[10,10,]),'opcion_fit':([4,6,],[11,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> mkdisk_command','command',1,'p_command','sintactico.py',6),
  ('command -> execute_command','command',1,'p_command','sintactico.py',7),
  ('mkdisk_command -> MKDISK opciones','mkdisk_command',2,'p_mkdisk_command','sintactico.py',12),
  ('opciones -> opciones opciones_element','opciones',2,'p_opciones','sintactico.py',20),
  ('opciones -> opciones_element','opciones',1,'p_opciones','sintactico.py',21),
  ('opciones_element -> opcion_size','opciones_element',1,'p_opciones_element','sintactico.py',33),
  ('opciones_element -> opcion_path','opciones_element',1,'p_opciones_element','sintactico.py',34),
  ('opciones_element -> opcion_unit','opciones_element',1,'p_opciones_element','sintactico.py',35),
  ('opciones_element -> opcion_fit','opciones_element',1,'p_opciones_element','sintactico.py',36),
  ('opcion_size -> SIZE IGUAL NUMERO','opcion_size',3,'p_opcion_size','sintactico.py',42),
  ('opcion_path -> PATH IGUAL RUTA','opcion_path',3,'p_opcion_path','sintactico.py',49),
  ('opcion_path -> PATH IGUAL COMILLADOBLE RUTA COMILLADOBLE','opcion_path',5,'p_opcion_path','sintactico.py',50),
  ('opcion_unit -> UNIT IGUAL ID','opcion_unit',3,'p_opcion_unit','sintactico.py',62),
  ('opcion_fit -> FIT IGUAL ID','opcion_fit',3,'p_opcion_fit','sintactico.py',69),
  ('execute_command -> EXECUTE PATH IGUAL RUTA','execute_command',4,'p_execute_command','sintactico.py',79),
  ('execute_command -> EXECUTE PATH IGUAL COMILLADOBLE RUTA COMILLADOBLE','execute_command',6,'p_execute_command','sintactico.py',80),
]
